//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_token_key
    {
        public string cd_employee { get; set; }
        public Nullable<System.DateTime> dt_login { get; set; }
        public string nm_token_key { get; set; }
        public Nullable<int> tm_end_user { get; set; }
        public string nm_key_reset { get; set; }
    }
}
