//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOS.Web.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string administrator {
            get {
                return ResourceManager.GetString("administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out this field.  (BM0001).
        /// </summary>
        internal static string BM0001 {
            get {
                return ResourceManager.GetString("BM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numbers.  (BM0002).
        /// </summary>
        internal static string BM0002 {
            get {
                return ResourceManager.GetString("BM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only integer values. (BM0003).
        /// </summary>
        internal static string BM0003 {
            get {
                return ResourceManager.GetString("BM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numbers.  (BM0004).
        /// </summary>
        internal static string BM0004 {
            get {
                return ResourceManager.GetString("BM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {param}.  (BM0006).
        /// </summary>
        internal static string BM0006 {
            get {
                return ResourceManager.GetString("BM0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {param_0} and {param_1}. (BM0008).
        /// </summary>
        internal static string BM0008 {
            get {
                return ResourceManager.GetString("BM0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please lengthen this text to {param} characters or more. (BM0009).
        /// </summary>
        internal static string BM0009 {
            get {
                return ResourceManager.GetString("BM0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input {param} characters or less.  (BM0011).
        /// </summary>
        internal static string BM0011 {
            get {
                return ResourceManager.GetString("BM0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {param_0} digits before the decimal point {param_1} digits after the decimal point. (BM0014).
        /// </summary>
        internal static string BM0014 {
            get {
                return ResourceManager.GetString("BM0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date. (BM0015).
        /// </summary>
        internal static string BM0015 {
            get {
                return ResourceManager.GetString("BM0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter alphanumeric characters.  (BM0024).
        /// </summary>
        internal static string BM0024 {
            get {
                return ResourceManager.GetString("BM0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0} format. (BM0051).
        /// </summary>
        internal static string BM0051 {
            get {
                return ResourceManager.GetString("BM0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the data..
        /// </summary>
        internal static string DbSaveErrorMessage {
            get {
                return ResourceManager.GetString("DbSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user has changed the data already. Please search again to get the latest data..
        /// </summary>
        internal static string DbUpdateConcurrencyError {
            get {
                return ResourceManager.GetString("DbUpdateConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist result was denied: .
        /// </summary>
        internal static string DeniedContent {
            get {
                return ResourceManager.GetString("DeniedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift-JIS.
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered. Please contact with FMS adminstrator..
        /// </summary>
        internal static string ERPApiErrorMessage {
            get {
                return ResourceManager.GetString("ERPApiErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー値.
        /// </summary>
        internal static string ErrorValue {
            get {
                return ResourceManager.GetString("ErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password had been tried 5 times. Please contact administrator to unlock your account..
        /// </summary>
        internal static string FailedPasswordAttempt {
            get {
                return ResourceManager.GetString("FailedPasswordAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列数が不正です。.
        /// </summary>
        internal static string InvalidColumnSizeTextFieldFile {
            get {
                return ResourceManager.GetString("InvalidColumnSizeTextFieldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user id or password..
        /// </summary>
        internal static string InvalidUserIdOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserIdOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL is not permitted..
        /// </summary>
        internal static string NotNullAllow {
            get {
                return ResourceManager.GetString("NotNullAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not have the data to be uploaded..
        /// </summary>
        internal static string NoUploadDataError {
            get {
                return ResourceManager.GetString("NoUploadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value exceeds the specified number of digits. Set up to half-width {0} digits and full-width {1} digits..
        /// </summary>
        internal static string OutOfLengthTextField {
            get {
                return ResourceManager.GetString("OutOfLengthTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range. Please set a number between {0} and {1}..
        /// </summary>
        internal static string OutOfRangeTextField {
            get {
                return ResourceManager.GetString("OutOfRangeTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key constraint violation..
        /// </summary>
        internal static string PrimaryKeyViolation {
            get {
                return ResourceManager.GetString("PrimaryKeyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行.
        /// </summary>
        internal static string RecordNumber {
            get {
                return ResourceManager.GetString("RecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the service..
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
